# Generated by Django 4.1.2 on 2022-11-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AtmAjax', '0002_alter_userinfo_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='card_number',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
    ]
